require "user.function"
require "user.autocmd"
--require "user.options"
--require "user.keymaps"
require "user.plugins"
--require "user.colorscheme"
--require "user.telescope"
--require "user.treesitter"
--require "user.nvim-tree"
--require "user.lualine"
--require "user.toggleterm"
--require "user.project"
--require "user.alpha"
--require "user.whichkey"
--require "user.mdpreview"
--require "user.cmp"
--require "user.lsp"

-- base
-- require "base.plugins"
require "base.keymaps"
-- require "base.bufferline"
require "base.options"
require "base.telescope"
require "base.project"
require "base.nvim-tree"
require "base.whichkey"
require "base.toggleterm"
require "base.cmp"
-- require "base.icons"
require "base.colorscheme"
-- require "base.treesitter"
require "base.alpha"
-- require "base.ts-rainbow"
